# Generated by Django 5.2.4 on 2025-07-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_availability_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='trainer_member',
        ),
    ]
