# Generated by Django 5.2.3 on 2025-06-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trainer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialties', models.CharField(blank=True, help_text="e.g., 'Yoga, Pilates, Strength Training'", max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
            ],
        ),
    ]
