# Generated by Django 5.2.3 on 2025-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trainerutilization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerutilization',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
