# Generated by Django 5.2.4 on 2025-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='member',
        ),
    ]
